# Spring boot application
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://jinlie2019db.rwlb.rds.aliyuncs.com/db_jinlieai?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: mingpian_dev
    password: Jinlie2019
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
